feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: VietNamese-SL
num_epoch: 20
python_evaluate: False
work_dir: ./work_dir/VietNamese-SL_phase1/
batch_size: 2
random_seed: 0
test_batch_size: 2
num_worker: 8
device: 0
log_interval: 200
eval_interval: 1
save_interval: 5
loss_weights:
  ConvCTC: 1.0
  SeqCTC: 1.0
  Dist: 25.0

# Load weights từ Phoenix2014-T, bỏ qua classifier do khác số từ vựng
load_weights: ./checkpoints/phoenix14t.pt
ignore_weights: ['classifier.weight', 'classifier.bias', 'conv1d.fc.weight', 'conv1d.fc.bias']
# Đóng băng mạng CNN Backbone để train phần chuỗi (warm-up)
freeze_conv2d: True

# Cấu hình Weights & Biases
use_wandb: True
wandb_project: 'VSL_Training'
wandb_name: 'Phase1_Freeze_Backbone'

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 10, 15]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0  # 0-1 represents ratio, >1 represents absolute value
  input_size: 224

model: slr_network.SLRModel
decode_mode: beam
model_args:
  num_classes: 2000 # THAY ĐỔI: Thành (tổng số từ vựng VSL + 1)
  c2d_type: resnet18 #resnet18, mobilenet_v2, squeezenet1_1, shufflenet_v2_x1_0, efficientnet_b1, mnasnet1_0, regnet_y_800mf, vgg16_bn, vgg11_bn, regnet_x_800mf, regnet_x_400mf, densenet121, regnet_y_1_6gf
  conv_type: 2
  use_bn: 1
